name: Lint & Prettier

on:
  push:
    branches:
      - main
      - develop
  pull_request:

jobs:
  lint-and-prettier:
    name: Run Lint & Prettier
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'

      - name: Install dependencies (backend)
        working-directory: unicare-backend
        run: npm install

      - name: Run ESLint (backend)
        working-directory: unicare-backend
        run: npm run lint

      - name: Run Prettier (backend)
        working-directory: unicare-backend
        run: npm run format

